name: Publish Docker image

on:
 push:
    branches:
      - 'main' 

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build Python app
        run: docker build -t ghcr.io/danknil/python-app:1.0 python-app

      - name: Docker push Python app
        run: docker push ghcr.io/danknil/python-app:1.0

      - name: Docker build Node app
        run: docker build -t ghcr.io/danknil/node-app:1.0 node-app

      - name: Docker push Node app
        run: docker push ghcr.io/danknil/node-app:1.0
